### ISSUE TITLE
`on_rsp_qry_order` 返回的数据是 None

### ISSUE THREAD

**Issue by IvanLi-CN** [pseudocodes/ctp2rs#1]
感谢您的项目，让我能在 rust 下愉快地调用 CTP。

我在 linux 环境下 + 上期 CTP 开发。我调用 `rsp_qry_order` 后，在 `on_rsp_qry_order` 只会收到 None。我尝试了 6.7.2、6.7.8 都是这样。使用 openCTP 没遇到问题。

具体来说：
  - **simnow 和中信仿真环境** 回调函数触发了和报单数量相同的次数，但 p_order 和 p_rsp_info 都是 None。
  - **OpenCTP** 正常返回
 
似乎 `on_rsp_qry_trade` 也是这样。
 
最小可复现的代码：[IvanLi-CN/ctp-qry-order](https://github.com/IvanLi-CN/ctp-qry-order)

ctp2rs 版本：0.1.3

**Comment by pseudocodes** [comment]
> 感谢您的项目，让我能在 rust 下愉快地调用 CTP。
> 
> 我在 linux 环境下 + 上期 CTP 开发。我调用 `rsp_qry_order` 后，在 `on_rsp_qry_order` 只会收到 None。我尝试了 6.7.2、6.7.8 都是这样。使用 openCTP 没遇到问题。
> 
> 具体来说：
> 
> * **simnow 和中信仿真环境** 回调函数触发了和报单数量相同的次数，但 p_order 和 p_rsp_info 都是 None。
> * **OpenCTP** 正常返回
> 
> 似乎 `on_rsp_qry_trade` 也是这样。
> 
> 最小可复现的代码：[IvanLi-CN/ctp-qry-order](https://github.com/IvanLi-CN/ctp-qry-order)
> 
> ctp2rs 版本：0.1.3

我刚用你的项目在 Macos 和 Linux 下用 6.7.2 版本都复现了一下 
这个例子判断写的不好 [这里](https://github.com/IvanLi-CN/ctp-qry-order/blob/ed20a70ea192515b23aa9d649dbf2237864232ec/src/trader_spi.rs#L186) 的判断的发生是 pRspInfo 为None 就会跳出，实际上 Simnow 在这个地方给 pRspInfo 的是空指针，即为 None , pOrder 是有值的

<img width="1969" alt="image" src="https://github.com/user-attachments/assets/5d3a3b81-6581-4927-866b-c663042214ba" />

**Comment by IvanLi-CN** [comment]
确实是这样，感谢~

我 debug 时看变量看错了，后悔没打印出来看看
